app/mod_landing_page/controllers.py
"""
Landing Page Module's Controllers
"""
from flask import Blueprint, render_template, request, send_from_directory, session
import time

from app import DB as db, REDIS as redis, REDIS_QUEUE as rqueue

from app.mod_tweet.forms import TweetForm

from app.mod_tweet.models import Tweet
from app.mod_auth.models import User

from app.mod_landing_page.tasks import bg_insert_tweet

from common import pretty_result, code

MOD_LANDING_PAGE = Blueprint('landing_page', __name__, url_prefix='/')


def insert_tweet(text, username):
    print(f"Inserting a Tweet")
    start = time.time()

    user = User.query.filter_by(name=username).first()
    tweet = Tweet(text, user=user)
    print(f"Creating a Tweet object: {tweet}")
    # tweet.insert()
    db.session.add(tweet)
    db.session.commit()

    end = time.time()
    time_elapsed = end - start
    return f"Stored to Database in {time_elapsed} ms"

@MOD_LANDING_PAGE.route('', methods=['GET', 'POST'])
def landing_page():
    """
    Return a HTML of Landing Page.
    """
    username = session['username']
    form = TweetForm(request.form)
    if form.validate_on_submit():
        task = rqueue.enqueue(bg_insert_tweet, form.tweet.data, username)
        form.tweet.data = ""
    tweets = Tweet.query.order_by(Tweet.id.desc()).limit(5)
    return render_template("landing_page/landing_page.html", username=username, tweets=tweets, form=form)

@MOD_LANDING_PAGE.route('/tweet', methods=['GET', 'POST'])
def get_tweet():
    """
    Return tweets
    """
    if request.method == 'GET':
        query_tweets = Tweet.query.order_by(Tweet.id.desc()).limit(5)
        tweets = []
        for query_tweet in query_tweets:
            tweets.append({
                'tweet': query_tweet.text, 
                'username': query_tweet.get_username(),
                'user_id': query_tweet.user_id,
            })
        return pretty_result(code.OK, data=tweets)
    else:
        result = insert_tweet(request.form['text'], request.form['username'])
        return result

@MOD_LANDING_PAGE.route('/robots.txt', methods=['GET', 'POST'])
def robots():
    """
    Return robot.txt file.
    """
    return send_from_directory('static/', filename='robots.txt')

app/templates/landing_page/landing_page.html
{% extends "layout.html" %} 

{% block title %}Twitter Flask{% endblock %} 

{% block appcontent %}
<div class="container">
  {% if username %}
  <div class="section">
    <div class="row">
      <div class="col s1"></div>
      <div class="col s10 m10">
        <div class="card horizontal">
          <div class="card-stacked">
            <div class="card-content">
              <form 
                class="col s12"
                method="POST" 
                action="{{ url_for('landing_page.landing_page') }}" 
                accept-charset="UTF-8" 
                role="form"
              >
                {{ form.csrf_token }}
                <div class="row">
                  <div class="input-field col s12">
                    {{ render_field(form.tweet, class="materialize-textarea", id="textarea1", placeholder="What are you thinking today?") }}
                  </div>
                </div>
                <button class="waves-effect waves-light btn indigo right" type="submit" name="submit">
                  Tweet
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="col s1"></div>
    </div>
  </div>
  <div class="divider"></div>
  {% endif %}
  {% for tweet in tweets %}
  <div class="section">
    <div class="row">
      <div class="col s2"></div>
      <div class="col s8 m8">
        <div class="card indigo darken-1">
          <div class="card-content white-text">
            <span class="card-title">@{{ tweet.get_username() }}</span>
            <p>
              {{ tweet.text }}
            </p>
            <p>{{ tweet.date_created }}</p>
          </div>
          <div class="card-action white-text">
            <a href="#">
              <span class="new badge"
                ><i class="tiny material-icons">thumb_up</i> {{ tweet.liked }}</span
              >
            </a>
            <a href="#">
              <span class="new badge"
                ><i class="tiny material-icons">repeat</i> {{ tweet.retweet }}</span
              >
            </a>
          </div>
        </div>
      </div>
      <div class="col s2"></div>
    </div>
  </div>
  <div class="divider"></div>
  {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/materialize.js') }}"></script>
<script>
  $(document).ready(function () {
      $('input#input_text, textarea#textarea1').characterCounter();
    });
</script>
{% endblock %}